before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:beineri/opt-qt532

    - sudo apt-get update -qq
    - sudo apt-get install -qq qt53-meta-full libboost-dev libavahi-compat-libdnssd-dev
    
    - wget https://www.dropbox.com/s/e0o670ve6gv1dgt/cmake-3.0.2-Linux-x86_64.tar.gz?dl=1 -O cmake-3.0.2-Linux-x86_64.tar.gz
    - tar zxf cmake-3.0.2-Linux-x86_64.tar.gz
    
    - wget https://www.dropbox.com/s/exjazsh5epqet2g/gcc_4.9.1-1_amd64.deb?dl=1 -O gcc_4.9.1-1_amd64.deb
    - sudo dpkg -i gcc_4.9.1-1_amd64.deb

script: 
  - source /opt/qt53/bin/qt53-env.sh
  - cmake-3.0.2-Linux-x86_64/bin/cmake . 
  - make 
