environment:
  QTDIR: c:\projects\i-score\iscore-windows-sdk\qt-5.6
  MINGW: c:\projects\i-score\iscore-windows-sdk\mingw32
  BOOST_ROOT: c:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\stage\lib
  JAMOMA_ROOT: c:\projects\i-score\iscore-windows-sdk\jamoma
  CHOCO_PATH: c:\ProgramData\chocolatey\bin
  CMAKE_PATH: c:\projects\i-score\iscore-windows-sdk\cmake


configuration: Release

install:
  - appveyor DownloadFile "https://www.dropbox.com/s/4hc09x926sa6w2k/iscore-windows-sdk.7z?dl=1" -FileName iscore-windows-sdk.7z
  - 7z x iscore-windows-sdk.7z -y > nul
  - iscore-windows-sdk/nsis.exe /S

build_script:
  - git submodule update --init --recursive
#  - cd base/addons
#  - git clone https://github.com/OSSIA/iscore-addon-csp
#  - cd iscore-addon-csp
#  - git submodule update --init --recursive
#  - cd ../../../
  - mkdir build
  - cd build
  - set PATH=%CMAKE_PATH%\bin;%QTDIR%\bin;%MINGW%\bin;
  - cmake -G"MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=CMake/Configurations/travis/appveyor-mingw-static-release.toolchain -DISCORE_CONFIGURATION=appveyor-mingw-static-release -DISCORE_SDK_PATH=c:/projects/i-score/iscore-windows-sdk ..
  - cmake --build . --target all_unity -- -j2
  - cpack

artifacts:
  - name: Installer
    path: 'build/i-score-*-win32.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: j0nBV9xVItdG3j6d0gHoyvrzi7TOhAy9/QIeyCbFeP8PTqq7DPr1oYwL5WIkPaXe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
