name: Linux distro build

on: push

jobs:
  fedora:
    name: Fedora 37
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Install git
        run: |
          dnf -y install git

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/fedora-qt6.deps.sh

      - name: Build
        run: |
          ./ci/fedora.build.sh

  suseleap:
    name: OpenSUSE Leap
    runs-on: ubuntu-latest
    container:
      image: opensuse/leap:latest

    steps:
      - name: Install git
        run: |
          zypper -n install git

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/suse-leap.deps.sh

      - name: Build
        run: |
          ./ci/suse.build.sh

  susetumbleweed:
    name: OpenSUSE Tumbleweed
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
      options: --privileged

    steps:
      - name: Install git
        run: |
          zypper -n install git

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/suse-tumbleweed.deps.sh

      - name: Build
        run: |
          ./ci/suse.build.sh

  archqt6:
    name: ArchLinux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install git
        run: |
          pacman -Syy --noconfirm
          pacman -S git --noconfirm

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/archlinux-qt6.deps.sh

      - name: Build
        run: |
          ./ci/archlinux-qt6.build.sh


  archqt6system:
    name: ArchLinux (System)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install git
        run: |
          pacman -Syy --noconfirm
          pacman -S git --noconfirm

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/archlinux-qt6-system.deps.sh

      - name: Build
        run: |
          ./ci/archlinux-qt6-system.build.sh
