name: Documentation build
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docs:
    name: Generate doxygen documentation
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: |
          sudo apt-get update -qq
          sudo apt-get remove -qq --force-yes clang* llvm* libllvm* libclang-*-dev
          sudo apt-get install -qq --force-yes git doxygen binutils build-essential cmake

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          ./ci/jammy.deps.sh

      - name: Configure
        run: |
          mkdir configure
          mkdir docs/Doxygen/headers
          cd configure
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_COMPILER=/usr/bin/clang-14 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-14
          find . -name '*.h' -exec mv {} ../docs/Doxygen/headers/ \;
          find . -name '*.hpp' -exec mv {} ../docs/Doxygen/headers/ \;

      - name: Build docs
        run: |
          (cd docs/Doxygen ; doxygen > doxygen.log)
          pwd
          ls
          mkdir build
          ls docs/Doxygen
          mv docs/Doxygen/output/html/* build/
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: ossia/score-api-docs
          token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: gh-pages
          folder: build
